### ISSUE TITLE
getting permission issue for install_packages

### ISSUE THREAD

**Issue by saip50** [bitnami/bitnami-docker-neo4j#8]
Hi,

I am running this docker file in AKS by setting up all environment variables, persistent volumes and deployment file. when building the image I am getting exception as:

```console
/bin/sh: 1: install_packages: Permission denied
The command '/bin/sh -c install_packages acl ca-certificates curl gzip jq libc6 procps tar zlib1g' returned a non-zero code: 126
##[error]The command '/bin/sh -c install_packages acl ca-certificates curl gzip jq libc6 procps tar zlib1g' returned a non-zero code: 126
##[error]The process '/usr/bin/docker' failed with exit code 126
```

Troubleshooting steps done:

1. changed "install_packages" to "install_packages.sh"
2. added "sudo" for the command
3. added "RUN chmod g+rwx /usr/sbin/install_packages.sh" in the dockerfile.

After all these steps, same issue persists. let me know if anyone knows about this.

**Comment by juan131** [comment]
Hi @saip50 

Please note you won't be able to run any privileged action (such as installing packages) AFTER changing the default user to 1001, see:

- https://github.com/bitnami/bitnami-docker-neo4j/blob/master/4/debian-10/Dockerfile#L31

Please note this container is a non-root container by default since version `3.4.3-r13` and that implies certain limitations:

- https://github.com/bitnami/bitnami-docker-neo4j#343-r13

**Comment by saip50** [comment]
Hi @juan131 

I also tried with this changes mentioned in, https://github.com/bitnami/bitnami-docker-neo4j#343-r13
by changing to user 1001 to root by using image version as "3.4.3-r13". still getting permission denied for the same.

**Comment by juan131** [comment]
Hi @saip50 

Please try the steps explained in the link below:

- https://github.com/bitnami/bitnami-docker-mariadb#extend-this-image

They explain how to workaround the privileged actions limitation.

> Note: this instructions are for MariaDB, but you can use equivalent ones in the Neo4j image.
